"use strict";

export const PROPETY_UPDATE_SUCCESSFUL = "PROPETY_UPDATE_SUCCESSFUL";
export const PROPERTIES_DATA_SUCCESS = "PROPERTIES_DATA_SUCCESS";

export const LOGIN_SUCCESSFUL = "LOGIN_SUCCESSFUL";
