"use strict";

export const PROPERTY_UPDATE_SUCCESSFUL = "PROPERTY_UPDATE_SUCCESSFUL";
export const PROPERTIES_DATA_SUCCESS = "PROPERTIES_DATA_SUCCESS";
export const DEMO_DATA_SUCCESS = "DEMO_DATA_SUCCESS";

export const LOGIN_SUCCESSFUL = "LOGIN_SUCCESSFUL";
